"""Verify Sunbeam preset metadata and annotated args rendering."""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from unittest.mock import patch

import pytest
import yaml

from rally_ci_churn.bootstrap import sunbeam


FAKE_IMAGES = [
    "ubuntu",
    "ubuntu-stress-ng",
    "ubuntu-fio",
    "ubuntu-netbench",
]

FAKE_FLAVORS = [
    "m1.tiny",
    "m1.small",
    "m1.benchmark",
    "m1.stress-ng",
    "m1.netbench",
]

FAKE_EXTERNAL_NETWORKS = ["external-network"]
FAKE_EXTERNAL_NETWORK_ID = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"

FAKE_SUBNETS = json.dumps([
    {"ID": "sub-1", "Name": "gtestos-subnet", "Network": "net-1"},
])
FAKE_NETWORKS = json.dumps([
    {"ID": "net-1", "Name": "gtestos-network"},
])
FAKE_DNS = "['10.0.0.1']"


def _fake_run_openstack(_clouds_yaml: Path, cloud_name: str, *args: str) -> str:
    joined = " ".join(args)
    if "image" in joined and "list" in joined:
        return "\n".join(FAKE_IMAGES)
    if "flavor" in joined and "list" in joined:
        return "\n".join(FAKE_FLAVORS)
    if "network" in joined and "list" in joined and "--external" in joined:
        return "\n".join(FAKE_EXTERNAL_NETWORKS)
    if "network" in joined and "list" in joined:
        return FAKE_NETWORKS
    if "network" in joined and "show" in joined:
        return FAKE_EXTERNAL_NETWORK_ID
    if "subnet" in joined and "list" in joined:
        return FAKE_SUBNETS
    if "subnet" in joined and "show" in joined:
        return FAKE_DNS
    raise RuntimeError(f"Unmocked openstack call: cloud={cloud_name} args={args}")


@pytest.fixture()
def fake_clouds(tmp_path: Path) -> Path:
    clouds_yaml = tmp_path / "clouds.yaml"
    clouds_yaml.write_text(
        textwrap.dedent(
            """\
            clouds:
              sunbeam:
                auth:
                  auth_url: https://keystone.example.com:5000/v3
                  username: admin
                  password: secret
                  project_name: admin
                  user_domain_name: default
                  project_domain_name: default
                region_name: RegionOne
              sunbeam-admin:
                auth:
                  auth_url: https://keystone.example.com:5000/v3
                  username: admin
                  password: secret
                  project_name: admin
                  user_domain_name: default
                  project_domain_name: default
                region_name: RegionOne
            """
        ),
        encoding="utf-8",
    )
    return clouds_yaml


def _load_config(clouds_yaml: Path) -> dict[str, object]:
    return yaml.safe_load(clouds_yaml.read_text(encoding="utf-8"))


class TestAnnotatedPresetRendering:
    @patch.object(sunbeam, "_run_openstack", side_effect=_fake_run_openstack)
    def test_smoke_render_is_annotated_and_parseable(self, _mock, fake_clouds: Path) -> None:
        config = _load_config(fake_clouds)
        args, task_path = sunbeam.build_preset("smoke", fake_clouds, config)

        assert "image_prep" not in args
        rendered = sunbeam.render_preset_args("smoke", args)

        assert rendered.startswith("# Generated by rally_ci_churn.bootstrap.sunbeam.")
        assert "# Preset: smoke" in rendered
        assert "# Usage tier: connectivity check" in rendered
        assert "# Recommended next preset: steady" in rendered
        assert "# Required services: Nova, Neutron, Swift" in rendered
        assert task_path == "tasks/autonomous_vm_waves.yaml.j2"

        parsed = yaml.safe_load(rendered)
        assert parsed["scenario"]["name"] == "CIChurn.boot_autonomous_vm"
        assert parsed["workload"]["profile"] == "smoke"

    @patch.object(sunbeam, "_run_openstack", side_effect=_fake_run_openstack)
    def test_net_many_to_one_render_calls_out_http_only_section(self, _mock, fake_clouds: Path) -> None:
        config = _load_config(fake_clouds)
        args, _task_path = sunbeam.build_preset("net-many-to-one", fake_clouds, config)

        rendered = sunbeam.render_preset_args("net-many-to-one", args)

        assert "Only used when traffic.mode is http_volume." in rendered
        parsed = yaml.safe_load(rendered)
        assert parsed["traffic"]["mode"] == "iperf3"
        assert parsed["server_volume"]["size_gib"] == 2


class TestPresetStructure:
    @pytest.mark.parametrize(
        ("preset", "unexpected_keys"),
        [
            ("steady", {"image_prep"}),
            ("fio-distributed", {"storage", "workload"}),
            ("net-ring", {"storage", "workload"}),
        ],
    )
    @patch.object(sunbeam, "_run_openstack", side_effect=_fake_run_openstack)
    def test_build_preset_excludes_irrelevant_sections(
        self,
        _mock,
        fake_clouds: Path,
        preset: str,
        unexpected_keys: set[str],
    ) -> None:
        config = _load_config(fake_clouds)
        args, _task_path = sunbeam.build_preset(preset, fake_clouds, config)

        for key in unexpected_keys:
            assert key not in args

    @pytest.mark.parametrize("preset", sorted(sunbeam.PRESET_DEFINITIONS))
    @patch.object(sunbeam, "_run_openstack", side_effect=_fake_run_openstack)
    def test_preset_definition_task_path_matches_builder(self, _mock, fake_clouds: Path, preset: str) -> None:
        config = _load_config(fake_clouds)
        _args, task_path = sunbeam.build_preset(preset, fake_clouds, config)

        assert task_path == sunbeam.get_preset_definition(preset).task_path


class TestSunbeamMain:
    @patch.object(sunbeam, "_run_openstack", side_effect=_fake_run_openstack)
    def test_main_writes_annotated_args_and_guidance(
        self,
        _mock,
        fake_clouds: Path,
        tmp_path: Path,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        args_path = tmp_path / "smoke.yaml"
        adminrc_path = tmp_path / "adminrc"

        rc = sunbeam.main(
            [
                "--clouds-yaml",
                str(fake_clouds),
                "--preset",
                "smoke",
                "--output-args",
                str(args_path),
                "--output-adminrc",
                str(adminrc_path),
            ]
        )

        assert rc == 0
        assert args_path.exists()
        assert adminrc_path.exists()
        assert args_path.read_text(encoding="utf-8").startswith(
            "# Generated by rally_ci_churn.bootstrap.sunbeam."
        )

        output = capsys.readouterr().out
        assert "role: connectivity check" in output
        assert "next: steady" in output
